-- ============================================================
-- Employee Performance & Workforce Intelligence
-- Data Loading
-- ============================================================
--
-- This project uses Python for bulk data generation and ETL.
--
-- Python pipeline responsibilities:
--   1. Generate 100k+ employee records
--   2. Generate related project and assignment data
--   3. Generate performance reviews
--   4. Generate SCD Type 2 employee history
--   5. Load OLTP data
--   6. Transform and load the Data Warehouse
--
-- This SQL file handles static reference data and documents
-- the database loading workflow.
-- ============================================================


-- ============================================================
-- OLTP DATABASE
-- ============================================================

USE greenfield_oltp;


-- ------------------------------------------------------------
-- Department Reference Data
-- ------------------------------------------------------------

INSERT INTO departments (
    department_id,
    department_name
)
VALUES
    (1, 'Sales'),
    (2, 'Research & Development'),
    (3, 'Human Resources')
ON DUPLICATE KEY UPDATE
    department_name = VALUES(department_name);


-- ------------------------------------------------------------
-- Bulk Data Loading
-- ------------------------------------------------------------
--
-- Employee records:
--   Generated by:
--   etl/synthesizer.py
--
-- Source/output:
--   data/generated/employees_100k.csv
--
-- Project and related data:
--   Generated by:
--   etl/generate_related_data.py
--
-- Source/output:
--   data/generated/projects.csv
--   data/generated/employee_projects.csv
--
-- Performance reviews:
--   Generated and loaded through the Python ETL pipeline.
--
-- These datasets are intentionally loaded through Python rather
-- than SQL because the project requires synthetic data generation,
-- transformation, validation, and SCD Type 2 processing.


-- ============================================================
-- DATA WAREHOUSE
-- ============================================================

USE greenfield_dw;


-- ------------------------------------------------------------
-- Dimension and Fact Loading
-- ------------------------------------------------------------
--
-- The following warehouse tables are populated by the Python
-- ETL pipeline:
--
--   dim_department
--   dim_employee
--   dim_project
--   dim_date
--   fact_performance_reviews
--
-- SCD Type 2 employee history is handled by the ETL process.
--
-- Runtime department changes from the Streamlit application
-- are handled through managers/scd2_manager.py.